Repository pyfar/spharpy, pull requests merged in 2023-10, with the labels that each got.

#33 Refactor/samplings
  .gitignore
  docs/conf.py
  examples/plane_wave_decomposition.ipynb
  examples/spherical_harmonics.ipynb
  requirements_dev.txt
  spharpy/_deprecation.py
  spharpy/interpolate.py
  spharpy/plot/spatial.py
  spharpy/samplings/__init__.py
  spharpy/samplings/_eqsp/__init__.py
  spharpy/samplings/_eqsp/samplings_fliege.mat
  spharpy/samplings/_eqsp/samplings_lebedev.py
  spharpy/samplings/coordinates.py
  spharpy/samplings/helpers.py
  spharpy/samplings/samplings.py
  spharpy/spatial/spatial.py
  spharpy/spherical.py
  tests/test_coordinate_transforms.py
  tests/test_coordinates.py
  tests/test_interpolate.py
  tests/test_samplings.ipynb
  tests/test_samplings.py
Labels: v1.0.0

#36 remove spharpy Coordinates
  examples/general_beamforming_weights.ipynb
  examples/plane_wave_decomposition.ipynb
  examples/spherical_harmonics.ipynb
  spharpy/__init__.py
  spharpy/_deprecation.py
  spharpy/interpolate.py
  spharpy/plot/spatial.py
  spharpy/samplings/__init__.py
  spharpy/samplings/coordinates.py
  spharpy/samplings/helpers.py
  spharpy/samplings/interior.py
  spharpy/samplings/samplings.py
  spharpy/spherical.py
  tests/conftest.py
  tests/test_beamforming.py
  tests/test_coordinate_transforms.py
  tests/test_coordinates.py
  tests/test_rotations.py
  tests/test_samplings.py
  tests/test_samplings_interior.py
Labels: v1.0.0

#44 Bugfix/spatial module
  spharpy/__init__.py
Labels: v1.0.0

#46 Improve and harmonize beamforming module docstrings
  spharpy/beamforming/beamforming.py
Labels: enhancement, v1.0.0

#47 Remove indexing submodule
  docs/modules.rst
  docs/spharpy.indexing.rst
  examples/general_beamforming_weights.ipynb
  spharpy/__init__.py
  spharpy/beamforming/beamforming.py
  spharpy/indexing/__init__.py
  spharpy/indexing/channel_indexing.py
  spharpy/spherical.py
  tests/test_acn_nm_indexing.py
  tests/test_aperture.py
  tests/test_indexing.py
Labels: refactoring

#45 Add Example notebooks to Sphinx
  .circleci/config.yml
  .readthedocs.yml
  CONTRIBUTING.rst
  docs/conf.py
  docs/general_beamforming_weights.nblink
  docs/index.rst
  docs/plane_wave_decomposition.nblink
  docs/rtd_environment.yml
  docs/spherical_harmonics.nblink
  examples/general_beamforming_weights.ipynb
  examples/plane_wave_decomposition.ipynb
  examples/spherical_harmonics.ipynb
  requirements_dev.txt
Labels: documentation, v1.0.0
