Repository pyfar/spharpy, pull requests merged in 2025-06, with the labels that each got.

#138 Doc: fix referencing in spherical submod
  spharpy/spherical.py
Labels: documentation

#142 Deprecate scipy Spherical Harmonics function
  pyproject.toml
  spharpy/samplings/interior.py
  spharpy/special.py
  tests/test_special.py
Labels: external deprecation

#144 Fix secondary sidebar display of class attributes
  docs/conf.py
Labels: documentation

#158 Correct quadrature flag for Fliege grid
  spharpy/samplings/samplings.py
  tests/test_samplings.py
Labels: bug

#101 Add Spherical Harmonics class
  spharpy/spherical.py
  tests/test_sh_class.py
Labels: enhancement

#160 Move SH class to sphary.classes
  spharpy/__init__.py
  spharpy/classes/__init__.py
  spharpy/classes/sh.py
  spharpy/spherical.py
  tests/test_sh_class.py
Labels: documentation
