Repository pyfar/spharpy, pull requests merged in 2025-04, with the labels that each got.

#102 Implement different normalization and phase conventions for spherical harmonic basis matrices
  spharpy/special.py
  spharpy/spherical.py
  tests/data/Y_cmplx_Condon-Shortley_maxN_acn.csv
  tests/data/Y_cmplx_Condon-Shortley_maxN_fuma.csv
  tests/data/Y_cmplx_Condon-Shortley_n3d_acn.csv
  tests/data/Y_cmplx_Condon-Shortley_n3d_fuma.csv
  tests/data/Y_cmplx_Condon-Shortley_sn3d_acn.csv
  tests/data/Y_cmplx_Condon-Shortley_sn3d_fuma.csv
  tests/data/Y_cmplx_None_maxN_acn.csv
  tests/data/Y_cmplx_None_maxN_fuma.csv
  tests/data/Y_cmplx_None_n3d_acn.csv
  tests/data/Y_cmplx_None_n3d_fuma.csv
  tests/data/Y_cmplx_None_sn3d_acn.csv
  tests/data/Y_cmplx_None_sn3d_fuma.csv
  tests/data/Y_real_Condon-Shortley_maxN_acn.csv
  tests/data/Y_real_Condon-Shortley_maxN_fuma.csv
  tests/data/Y_real_Condon-Shortley_n3d_acn.csv
  tests/data/Y_real_Condon-Shortley_n3d_fuma.csv
  tests/data/Y_real_Condon-Shortley_sn3d_acn.csv
  tests/data/Y_real_Condon-Shortley_sn3d_fuma.csv
  tests/data/Y_real_None_maxN_acn.csv
  tests/data/Y_real_None_maxN_fuma.csv
  tests/data/Y_real_None_n3d_acn.csv
  tests/data/Y_real_None_n3d_fuma.csv
  tests/data/Y_real_None_sn3d_acn.csv
  tests/data/Y_real_None_sn3d_fuma.csv
  tests/test_spherical_harmonics.py
Labels: enhancement

#111 deprecate python 3.8
  .circleci/config.yml
  README.md
  pyproject.toml
Labels: bug

#112 Fix wrong package info in spharpy.rst
  docs/spharpy.rst
Labels: documentation
